#!/usr/bin/bash

if ! grep -q "^docker:" /etc/group; then
    grep "^docker:" /usr/lib/group | tee -a /etc/group >/dev/null
fi

wheelarray=($(getent group wheel | cut -d ":" -f 4 | tr ',' '\n'))
for user in $wheelarray; do
    usermod -aG docker $user
done
